apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "service.labels" . | nindent 4 }}
  name: "{{ include "service.fullname" . }}-{{ .Values.env }}-config"
data:
{{ .Files.Get (printf "conf/%s/app.conf" .Values.env) | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "service.fullname" . }}-splunk-{{ .Values.env }}-config"
data:
{{ .Files.Get (printf "conf/%s/splunk.conf" .Values.env) | indent 2 }}