{{- if .Values.ingress.enabled -}}
{{- $fullName := include "service.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "{{ $fullName }}-{{ .Values.env }}.{{ .Values.cluster }}.app.apple.com"
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backend:
    serviceName: {{ include "service.fullname" . }}
    servicePort: {{ .Values.service.port }}
{{- end }}